### ISSUE TITLE
Songs not playing on either overwrite or playlist mode

### ISSUE THREAD

**Issue by Myonoron** [iLollek/NRPFarMod#28]
When using overwrite mode, I cant press play no matter what.
When using Playlist mode, it only plays the games' OST, when it comes around to loading my songs in, which are in .mp3 format like Ive been instructed to do, it throws an error message:
"System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NRPFarmod.NRPFarModLib.CheckAndUpdateSong()+MoveNext()"

**Comment by iLollek** [comment]
Hello!

> which are in .mp3 format like Ive been instructed to do

If I understand you correctly, you're putting Sound Files in the MPEG3 Format (.mp3) into the /src/ Folder of NRPFarMod?
If that's the case, then this Error is expected. I don't know who instructed you to put .mp3 files there, but actually, NRPFarMod expects you to put WAVE Audiofiles (.wav) there. 

Here's the according section of the [README.md](https://github.com/iLollek/NRPFarMod?tab=readme-ov-file#usage-how-to-import-your-songs-from-youtube--spotify)

> [...] then convert the output into WAVE (.wav) and then put that Music into your /src/ Folder.

If you convert your .mp3 files into .wav using a [Converter Tool](https://offlineconverter.com/audio/mp3-to-wav/) and then placing your .wav Files into the /src/ Folder, you should be able to listen to your Music while playing the game, be that in Playlist mode or Overwrite mode.

Please respond to this Ticket if you have any more questions, or if this fixed your Issue (so that I can close it.)

Thank you!

**Comment by Myonoron** [comment]
Hey again, update on this situation lol.
so my memory was kind of fogged, i forgot its wav instead of mp3. i do indeed have wav files in there, but they seem to be simply converted wrong somehow. am trying to convert the original mp3 files to wav through the link you provided :)

**Comment by iLollek** [comment]
and converting your mp3 files to wav and putting the wav files into the /src/ folder gives you the same error?

**Comment by Myonoron** [comment]
yeah, i used a different mp3 to wav converter, and it worked. Closing this, cause of error was a simple skill issue lol
